### ISSUE TITLE
Create a new article for Sitecore 8.1 + Azure Web App

### ISSUE THREAD

**Issue by ob1dev** [olegburov/sitecore-azure-content#1]
Create a new article 'How to deploy Sitecore 8.1 solution to Microsoft Azure Web App using Visual Studio' using the [previous version](https://github.com/olegburov/Sitecore-Azure-Content/blob/master/articles/how-to-deploy-sitecore-80-solution-to-microsoft-azure-web-app-using-visual-studio.md) as a template.

**Comment by ivansharamok** [comment]
Added article for 8.1

**Comment by ob1dev** [comment]
The article has been implemented and published.
