### ISSUE TITLE
Registry Access in Azure

### ISSUE THREAD

**Issue by rhysbharris** [olegburov/sitecore-azure-content#3]
Hi, great post by the way.  I just was wondering if you have a fix for an issue that I have seen running 8.1 in Azure web app.  In the log I see:

```
WARN  Failed to create counter 'Sitecore.Jobs\Jobs | Jobs Executed / sec'. Sitecore has no necessary permissions for reading/creating counters.
        Message: Access to the registry key 'Global' is denied.
WARN  Failed to create counter 'Sitecore.Jobs\Pipelines | Pipelines Aborted / sec'. Sitecore has no necessary permissions for reading/creating counters.
        Message: Access to the registry key 'Global' is denied."
```

In the old cloud service deployment method we can run the `startup.cmd` task to set permissions, but do you know if there is an equivalent in Azure web apps/app services?

**Comment by ob1dev** [comment]
Azure Web Apps do not support Windows Performance counter. Please see the [Access performance counter programmatically in Microsoft Azure web app](http://stackoverflow.com/questions/29632001/access-performance-counter-programmatically-in-microsoft-azure-web-app) post at StackOverflow for more details.

As a workaround, you can disable performance counter in the `\Website\App_Config\Sitecore.config` file:
1. Swith the `Counters.Enabled` setting to the `false` value:
   
   ``` xml
   <setting name="Counters.Enabled" value="false"/>
   ```
2. Comment out or remove the `HealthMonitor` processor:
   
   ``` xml
   <processor type="Sitecore.Pipelines.HealthMonitor.HealthMonitor, Sitecore.Kernel" method="LogCounterStatus">
    <counters hint="raw:AddCounter">
     ...
    </counters>
   </processor>
   ```
3. Comment out or remove the `CounterDumpAgent` agent:
   
   ``` xml
   <agent type="Sitecore.Tasks.CounterDumpAgent" method="Run" interval="01:00:00">
    <DumpFile>
      $(dataFolder)/diagnostics/counters.{date}.{time}.{processid}.txt
    </DumpFile>
   </agent>
   ```
4. Comment out or remove the `MemoryMonitorHook` hook:
   
   ``` xml
   <hook type="Sitecore.Diagnostics.MemoryMonitorHook, Sitecore.Kernel">
    <param desc="Threshold">2GB</param>
    <param desc="Check interval">00:00:05</param>
    <param desc="Minimum time between log entries">00:01:00</param>
    <ClearCaches>false</ClearCaches>
    <GarbageCollect>false</GarbageCollect>
    <AdjustLoadFactor>false</AdjustLoadFactor>
   </hook>
   ```

**Comment by ob1dev** [comment]
Please let me know if that helps you to get rid of these warning or not.
